### ISSUE TITLE
Little Fish Big Tale

### ISSUE THREAD

**Issue by polluks** [oss003/VIC20-MPAGD-Suite#1]
So how about a second try?
http://sleepingelephant.com/~sleeping/ipw-web/bulletin/bb/viewtopic.php?t=9675&sid=cca735b491c3fd870571634f271fb88c
https://spectrumcomputing.co.uk/entry/34808/ZX-Spectrum/Little_Fish_Big_Tale
http://sleepingelephant.com/~sleeping/ipw-web/bulletin/bb/viewtopic.php?t=9086

**Comment by oss003** [comment]
Hi Polluks, the VIC port of MPAGD will be a standard port for 16x16 sprites. Little Fish Big Tale was written in AGDmini which uses 8x8 sprites. Maybe in the future this option can be added.
